version: "3.7"

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    volumes:
      - /docker/postgres/data/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: golang
      POSTGRES_PASSWORD: golang
    ports:
      - "5432:5432"
    networks:
      - backend

  go:
    container_name: go
    build:
      context: .
      dockerfile: docker/go/Dockerfile
    ports:
      - "8080:8080" # Forward the exposed port 8080 on the container to port 8080 on the host machine
    depends_on:
      - "postgres"
    networks:
      - backend

  web:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    ports:
      - "80:8080"
    volumes:
      - ./frontend:/app
      - ./frontend/node_modules:/app/node_modules
    networks:
      - backend

networks:
  backend: